<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1524f249190e187896ab9d4c57e461e4
{
    public static $files = array (
        'a54983ad8cdf63e7aaa35534acdcc96c' => __DIR__ . '/../..' . '/Core/Routing.php',
    );

    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Modules\\Homepage\\Models\\' => 24,
            'Modules\\Homepage\\Controllers\\' => 29,
            'Modules\\About\\Models\\' => 21,
            'Modules\\About\\Controllers\\' => 26,
            'Models\\' => 7,
        ),
        'L' => 
        array (
            'Libraries\\AssetManager\\' => 23,
        ),
        'C' => 
        array (
            'Core\\' => 5,
            'Controllers\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Modules\\Homepage\\Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/Homepage/Models',
        ),
        'Modules\\Homepage\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/Homepage/Controllers',
        ),
        'Modules\\About\\Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/About/Models',
        ),
        'Modules\\About\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/About/Controllers',
        ),
        'Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Models',
        ),
        'Libraries\\AssetManager\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Libraries/AssetManager',
        ),
        'Core\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Core',
        ),
        'Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Controllers',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1524f249190e187896ab9d4c57e461e4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1524f249190e187896ab9d4c57e461e4::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
