<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'a54983ad8cdf63e7aaa35534acdcc96c' => $baseDir . '/Core/Routing.php',
);
