language: php

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - mkdir nsy
  - composer update
  - composer install --prefer-source --no-interaction

script:
  - phpunit

env:
  - APP_ENV=development
  - APP_DIR=nsy
  - DB_CONNECTION=mysql
