language: php

php:
  - 7.4
  - 8.2

before_script:
  - mkdir nsy
  - composer update
  - composer install --prefer-source --no-interaction

script:
  - phpunit System/Test/SimpleTest.php

env:
  - APP_ENV=development
  - APP_DIR=nsy
  - DB_CONNECTION=mysql
