#!/bin/bash
run_help() {
	printf "NAME :\n"
	printf " NSY Command Line Interface\n\n"
	printf "USAGE :\n"
	printf " * nsy [command] [command options] [arguments...]\n"
	printf " * nsy [command] [arguments...]\n\n"
	printf "VERSION :\n"
	printf " %s\n\n" "$NSY_CLI_VERSION"
	printf "AUTHOR :\n"
	printf " Vikry Yuansah\n\n"
	printf "LINK :\n"
	printf " https://github.com/kazuyamarino/nsy/blob/master/docs/OVERVIEW.md\n\n"

	printf "COMMANDS :\n"
	printf " --install\t\t Install or update NSY CLI\n"
	printf " --hello\t\t Show welcome message\n"
	printf " --help\t\t\t Show help\n"
	printf " --version\t\t Show NSY CLI version\n"
	printf " --setup\t\t Setting up NSY for ready to use\n"
	printf " serve\t\t\t Start the PHP built-in dev server (default: 127.0.0.1:8000)\n"
	printf " dump:autoload\t\t Run 'composer dump-autoload -o'\n"
	printf " dump:mysql\t\t Dump a MySQL database\n"
	printf " show:module\t\t List HMVC modules\n"
	printf " show:controller\t List MVC or HMVC controller files\n"
	printf " show:model\t\t List MVC or HMVC model files\n"
	printf " show:migrate\t\t List migration class files\n"
	printf " make:controller\t Create a MVC or HMVC controller\n"
	printf " make:model\t\t Create a MVC or HMVC model\n"
	printf " make:migrate\t\t Create a timestamped migration class file\n"
	printf " make:module\t\t Create an HMVC module directory\n"
	printf " make:route\t\t Create a route file\n"
	printf " make:view\t\t Create a MVC or HMVC view file\n"
	printf " make:middleware\t\t Create a middleware class\n"
	printf " run:migrate\t\t Run migration class file(s)\n\n"

	printf "COMMAND OPTIONS :\n"
	printf " mvc\t set the command value for mvc mode\n"
	printf " hmvc\t set the command value for hmvc mode\n"
	printf " all\t run all migration classes\n"
	printf " list\t select a migration class from a list\n"
	printf " up|down\t migration direction for run:migrate (default: up)\n\n"

	printf "ARGUMENTS... :\n"
	printf " mode\t\t\t set the mode (mvc or hmvc)\n"
	printf " controller-name\t controller class name\n"
	printf " model-name\t\t model class name\n"
	printf " module-name\t\t HMVC module directory name\n"
	printf " migration-name\t\t migration class name\n"
	printf " route-name\t\t route file name\n"
	printf " view-name\t\t view file name\n"
	printf " middleware-name\t middleware class name\n"
	printf " port\t\t\t dev server port for 'serve' (default: 8000)\n"
}
