#!/bin/bash
run_help() {
	printf "NAME :\n"
	printf " NSY Command Line Interface\n\n"
	printf "USAGE :\n"
	printf " nsy command [command options] [arguments...]\n\n"
	printf "VERSION :\n"
	printf " 1.0.0\n\n"
	printf "AUTHOR :\n"
	printf " Vikry Yuansah\n\n"
	printf "LINK :\n"
	printf " https://github.com/kazuyamarino/nsy-docs/blob/master/USERGUIDE.md#nsy-cli-command-line\n\n"

	printf "COMMANDS :\n"
	printf " --install\t\t Install or update NSY CLI\n"
	printf " --hello\t\t Show welcome message \n"
	printf " --help\t\t\t Show help\n"
	printf " --setup\t\t Setting up NSY for ready to use\n"
	printf " dump:autoload\t\t Call composer dump-autoload with the optimize flag\n"
	printf " dump:mysql\t\t Dump mysql database\n"
	printf " show:module\t\t Show a list of HMVC modules directory\n"
	printf " show:controller\t Show a list of MVC or HMVC controller files\n"
	printf " show:model\t\t Show a list of MVC or HMVC model files\n"
	printf " show:migration\t\t Show a list of migration class file\n"
	printf " make:controller\t Create a MVC or HMVC controller directory\n"
	printf " make:model\t\t Create a MVC or HMVC model directory\n"
	printf " make:migration\t\t Create a migration class file\n"
	printf " make:module\t\t Create a HMVC module directory\n\n"

	printf "COMMAND OPTIONS :\n"
	printf " mvc\t set the command value for mvc mode\n"
	printf " hmvc\t set the command value for hmvc mode\n"
}
