<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '447a4b20400f11b7e33b56bd0d7b70b5' => $baseDir . '/Routing.php',
);
