<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Modules\\Homepage\\Models\\' => array($baseDir . '/Modules/Homepage/Models'),
    'Modules\\Homepage\\Controllers\\' => array($baseDir . '/Modules/Homepage/Controllers'),
    'Modules\\About\\Models\\' => array($baseDir . '/Modules/About/Models'),
    'Modules\\About\\Controllers\\' => array($baseDir . '/Modules/About/Controllers'),
    'Models\\' => array($baseDir . '/Models'),
    'Libraries\\AssetManager\\' => array($baseDir . '/Libraries/AssetManager'),
    'Core\\' => array($baseDir . '/Core'),
    'Controllers\\' => array($baseDir . '/Controllers'),
);
