<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita81005d879fb6ca0d6d94855e36bb35b
{
    public static $files = array (
        '447a4b20400f11b7e33b56bd0d7b70b5' => __DIR__ . '/../..' . '/Routing.php',
    );

    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Modules\\Homepage\\Models\\' => 24,
            'Modules\\Homepage\\Controllers\\' => 29,
            'Modules\\About\\Models\\' => 21,
            'Modules\\About\\Controllers\\' => 26,
            'Models\\' => 7,
        ),
        'L' => 
        array (
            'Libraries\\AssetManager\\' => 23,
        ),
        'C' => 
        array (
            'Core\\' => 5,
            'Controllers\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Modules\\Homepage\\Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/Homepage/Models',
        ),
        'Modules\\Homepage\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/Homepage/Controllers',
        ),
        'Modules\\About\\Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/About/Models',
        ),
        'Modules\\About\\Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Modules/About/Controllers',
        ),
        'Models\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Models',
        ),
        'Libraries\\AssetManager\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Libraries/AssetManager',
        ),
        'Core\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Core',
        ),
        'Controllers\\' => 
        array (
            0 => __DIR__ . '/../..' . '/Controllers',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita81005d879fb6ca0d6d94855e36bb35b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita81005d879fb6ca0d6d94855e36bb35b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
